language: node_js
node_js:
- '5.9'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
- gulp
deploy:
  provider: npm
  email: npm@airbug.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: T9ym8+sdVeW/V1K9CP/Fe5DpoKnR+0NFS60MhHRpXAdLcXoL16+GJAaZHLuRKoduBGKeFiCJRhbDleY2nTOJN1O+8Dr8KfoetjVMfIxnfed0T/T/xH/bzff9HMdXBi5de08TTjQiaQtQknLozm3/If4DYsLVILtkHha5wtMl1bpTwQ99kp8Fgxk8QUozthrCJ/ruoAnC3FSV1IrTVFCxktptgR9C6F/KYqnGzzp1xpmqnQ8Id7XLx0dEQxxCexJQpwGNrXMZc7ocuWPbuKDKxZkiT65qIBst3QdQMpjP/qAXh613YP0EIZeFJRm9hEH6Q8uLVtLSbcEoIFEiS9DNMXcSADelGK2MDtdsH2mLwDhVfkekH6hvB0YdY32kvmdJemzYApDAnzN4Tevk9WehoXqtW9x5imkgqh0oFqIuyRPuuNdZoZHnfLEb7fsxuyGE5WTK95fmpzZt2faZCS84u9MvgpL89w1RRBjIdCW/dDguGNu8IRpukgnMdxqc5259SXQnEvtmWi4UcJrj6KTbi53kOy8GkPK43aiWYoYvoXExhVTQd2B8o8yYiNWP8sFPA/pk7OnblPVIWOm/aCja45X1bew/bPrTXAiNCqu9ACT/G9vIw9NFAJX5AZPswzmmxzvtnY9krrTD62lb+I5du79tuYYEyONm2jPUVXZiX6U=
